#!/bin/bash
#
# identify -- control the password of VNC/Unix/sudo login
#
# Usage: identify 0|1 vnc|unix|sudo
#

identify=$1
account=$2

[ -z "$account" ] && account=vnc

DOCKER_DIR=$(cd $(dirname $0) && pwd)
CONFIG_DIR=$DOCKER_DIR/../configs/

LAB_IDENTIFY=$CONFIG_DIR/.${account}_identify

[ ! -f $LAB_IDENTIFY ] && echo 1 > $LAB_IDENTIFY

IDENTIFY=$(< $LAB_IDENTIFY)

if [ -z "$identify" ]; then
    # Switch if no identify argument pass
    if [ -n "$IDENTIFY" -a "$IDENTIFY" -eq 1 ]; then
	identify=0
    else
	identify=1
    fi
fi

if [ $identify -eq 0 ]; then
	echo "LOG: Disable password of $account"
	echo 0 > $LAB_IDENTIFY
else
	echo "LOG: Enable password of $account"
	echo 1 > $LAB_IDENTIFY
fi
