#!/bin/bash
#
# monitor -- monitor a docker lab
#

DOCKER_DIR=$(cd $(dirname $0) && pwd)
CONFIG_DIR=$DOCKER_DIR/../configs/

CONTAINER_ID=$1
if [ -z "$CONTAINER_ID" ]; then
    LAB_CONTAINER_ID=$CONFIG_DIR/.container_id
    if [ -f $LAB_CONTAINER_ID ]; then
        CONTAINER_ID=$(< $LAB_CONTAINER_ID)
    else
        echo "LOG: Container id or name required" && exit 1
    fi
fi

docker stats $CONTAINER_ID 2>&1
