#!/bin/bash
#
# open -- open the docker lab via a browser
#
# Usage: open [browser]
#

DOCKER_DIR=$(cd $(dirname $0) && pwd)
CONFIG_DIR=$DOCKER_DIR/../configs/

IMAGE=$(< $CONFIG_DIR/name)

LAB_HOST_NAME=$CONFIG_DIR/.host_name

[ -f $LAB_HOST_NAME ] && lab_host=$(< $LAB_HOST_NAME)
[ -z "$lab_host" ] && lab_host="localhost"

lab_name=`basename $IMAGE`

LAB_LOCAL_PORT=$CONFIG_DIR/.local_port
LAB_VNC_PWD=$CONFIG_DIR/.vnc_pwd

WEB_BROWSER=$1
[ -z "$WEB_BROWSER" ] && WEB_BROWSER=chromium-browser
which $WEB_BROWSER 2>&1 >/dev/null
[ $? -eq 1 ] && WEB_BROWSER=firefox

# Get login port
local_port=6080
[ -f $LAB_LOCAL_PORT ] && local_port=$(< $LAB_LOCAL_PORT)

# Get vnc page
url=http://$lab_host:$local_port/vnc.html

# Get login password
[ -f $LAB_VNC_PWD ] && pwd=$(< $LAB_VNC_PWD)
[ -z "$pwd" ] && pwd=ubuntu

# Create local shotcut on Desktop
REMOTE_DESKTOP_SHORTCUT=`find configs/ -name "lab.desktop"`
LOCAL_DESKTOP_SHORTCUT=~/Desktop/${lab_name}.desktop
if [ -d ~/Desktop ]; then
    echo '#!/usr/bin/env xdg-open' > $LOCAL_DESKTOP_SHORTCUT
    if [ "$WEB_BROWSER" == "chromium-browser" ]; then
        icon=chromium-browser.png
    else
        icon=firefox.png
    fi
    cat $REMOTE_DESKTOP_SHORTCUT | sed "s%Exec=.*%Exec=$WEB_BROWSER $url%g" | sed "s%terminator.png%$icon%g">> $LOCAL_DESKTOP_SHORTCUT
    chmod a+x $LOCAL_DESKTOP_SHORTCUT
fi

which $WEB_BROWSER 2>&1>/dev/null \
    && ($WEB_BROWSER $url 2>&1>/dev/null &) \
    && echo "Please login $url with password: $pwd"
